apiVersion: v1
kind: Pod                # pod
metadata:
  name: nginx
spec:
  containers:
  - name: main-ctr                             # main container
    image: caseyabbottthefirst/nginxadapter:1.0            # chaing the dockerhub account to your own
    ports:
    - containerPort: 80
  - name: helper-ctr                                 # helper container
    image: nginx/nginx-prometheus-exporter
    args: ["-nginx.scrape-uri","http://localhost/nginx_status"]
    ports:
    - containerPort: 9113